// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package sqldb

import (
	"context"
	"database/sql"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_log(
    id,
    table_name,
    record_id,
    action,
    before,
    after,
    timestamp
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
`

type CreateAuditLogParams struct {
	ID        string         `json:"id"`
	TableName string         `json:"table_name"`
	RecordID  string         `json:"record_id"`
	Action    string         `json:"action"`
	Before    sql.NullString `json:"before"`
	After     string         `json:"after"`
	Timestamp string         `json:"timestamp"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLog,
		arg.ID,
		arg.TableName,
		arg.RecordID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.Timestamp,
	)
	return err
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, table_name, record_id, "action", "before", "after", timestamp
FROM audit_log
WHERE action = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListAuditLogsByActionParams struct {
	Action string `json:"action"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByAction, arg.Action, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByTable = `-- name: ListAuditLogsByTable :many
SELECT id, table_name, record_id, "action", "before", "after", timestamp
FROM audit_log
WHERE table_name = ?
ORDER BY timestamp DESC
LIMIT ?
`

type ListAuditLogsByTableParams struct {
	TableName string `json:"table_name"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsByTable, arg.TableName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsForRecord = `-- name: ListAuditLogsForRecord :many
SELECT id, table_name, record_id, "action", "before", "after", timestamp
FROM audit_log
WHERE
    table_name = ?
    AND record_id = ?
ORDER BY timestamp DESC
`

type ListAuditLogsForRecordParams struct {
	TableName string `json:"table_name"`
	RecordID  string `json:"record_id"`
}

func (q *Queries) ListAuditLogsForRecord(ctx context.Context, arg ListAuditLogsForRecordParams) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsForRecord, arg.TableName, arg.RecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsRecent = `-- name: ListAuditLogsRecent :many
SELECT id, table_name, record_id, "action", "before", "after", timestamp
FROM audit_log
ORDER BY timestamp DESC
LIMIT ?
`

func (q *Queries) ListAuditLogsRecent(ctx context.Context, limit int64) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogsRecent, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.RecordID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
