// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package sqldb

import (
	"context"
	"database/sql"
)

const countEmployeesUsingCompensationPackage = `-- name: CountEmployeesUsingCompensationPackage :one
SELECT COUNT(*)
FROM employee
WHERE
    compensation_package_id = ?
    AND deleted_at IS NULL
`

func (q *Queries) CountEmployeesUsingCompensationPackage(ctx context.Context, compensationPackageID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmployeesUsingCompensationPackage, compensationPackageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employee(
    id,
    org_id,
    serial_num,
    full_name,
    display_name,
    address,
    email_address,
    phone_number,
    birth_date,
    gender,
    marital_status,
    num_dependents,
    num_children,
    cin_num,
    cnss_num,
    hire_date,
    position,
    compensation_package_id,
    bank_rib,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
    ?
) RETURNING id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
`

type CreateEmployeeParams struct {
	ID                    string         `json:"id"`
	OrgID                 string         `json:"org_id"`
	SerialNum             int64          `json:"serial_num"`
	FullName              string         `json:"full_name"`
	DisplayName           sql.NullString `json:"display_name"`
	Address               sql.NullString `json:"address"`
	EmailAddress          sql.NullString `json:"email_address"`
	PhoneNumber           sql.NullString `json:"phone_number"`
	BirthDate             string         `json:"birth_date"`
	Gender                string         `json:"gender"`
	MaritalStatus         string         `json:"marital_status"`
	NumDependents         int64          `json:"num_dependents"`
	NumChildren           int64          `json:"num_children"`
	CinNum                string         `json:"cin_num"`
	CnssNum               sql.NullString `json:"cnss_num"`
	HireDate              string         `json:"hire_date"`
	Position              string         `json:"position"`
	CompensationPackageID string         `json:"compensation_package_id"`
	BankRib               sql.NullString `json:"bank_rib"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, createEmployee,
		arg.ID,
		arg.OrgID,
		arg.SerialNum,
		arg.FullName,
		arg.DisplayName,
		arg.Address,
		arg.EmailAddress,
		arg.PhoneNumber,
		arg.BirthDate,
		arg.Gender,
		arg.MaritalStatus,
		arg.NumDependents,
		arg.NumChildren,
		arg.CinNum,
		arg.CnssNum,
		arg.HireDate,
		arg.Position,
		arg.CompensationPackageID,
		arg.BankRib,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :one
UPDATE employee
SET
    updated_at = ?,
    deleted_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
RETURNING id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
`

type DeleteEmployeeParams struct {
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, deleteEmployee, arg.UpdatedAt, arg.DeletedAt, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployee = `-- name: GetEmployee :one
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) GetEmployee(ctx context.Context, id string) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployee, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeeByOrgAndSerialNum = `-- name: GetEmployeeByOrgAndSerialNum :one
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
WHERE
    org_id = ?
    AND serial_num = ?
`

type GetEmployeeByOrgAndSerialNumParams struct {
	OrgID     string `json:"org_id"`
	SerialNum int64  `json:"serial_num"`
}

func (q *Queries) GetEmployeeByOrgAndSerialNum(ctx context.Context, arg GetEmployeeByOrgAndSerialNumParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeByOrgAndSerialNum, arg.OrgID, arg.SerialNum)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeeIncludingDeleted = `-- name: GetEmployeeIncludingDeleted :one
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
WHERE id = ?
`

func (q *Queries) GetEmployeeIncludingDeleted(ctx context.Context, id string) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeIncludingDeleted, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNextSerialNumber = `-- name: GetNextSerialNumber :one
SELECT COALESCE(MAX(serial_num), 0) + 1
FROM employee
WHERE org_id = ?
`

func (q *Queries) GetNextSerialNumber(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextSerialNumber, orgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hardDeleteEmployee = `-- name: HardDeleteEmployee :exec
DELETE FROM employee
WHERE id = ?
`

func (q *Queries) HardDeleteEmployee(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteEmployee, id)
	return err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
WHERE deleted_at IS NULL
ORDER BY org_id, serial_num
`

func (q *Queries) ListEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SerialNum,
			&i.FullName,
			&i.DisplayName,
			&i.Address,
			&i.EmailAddress,
			&i.PhoneNumber,
			&i.BirthDate,
			&i.Gender,
			&i.MaritalStatus,
			&i.NumDependents,
			&i.NumChildren,
			&i.CinNum,
			&i.CnssNum,
			&i.HireDate,
			&i.Position,
			&i.CompensationPackageID,
			&i.BankRib,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByOrganization = `-- name: ListEmployeesByOrganization :many
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
WHERE
    org_id = ?
    AND deleted_at IS NULL
ORDER BY serial_num
`

func (q *Queries) ListEmployeesByOrganization(ctx context.Context, orgID string) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesByOrganization, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SerialNum,
			&i.FullName,
			&i.DisplayName,
			&i.Address,
			&i.EmailAddress,
			&i.PhoneNumber,
			&i.BirthDate,
			&i.Gender,
			&i.MaritalStatus,
			&i.NumDependents,
			&i.NumChildren,
			&i.CinNum,
			&i.CnssNum,
			&i.HireDate,
			&i.Position,
			&i.CompensationPackageID,
			&i.BankRib,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByOrganizationIncludingDeleted = `-- name: ListEmployeesByOrganizationIncludingDeleted :many
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
WHERE org_id = ?
ORDER BY serial_num
`

func (q *Queries) ListEmployeesByOrganizationIncludingDeleted(ctx context.Context, orgID string) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesByOrganizationIncludingDeleted, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SerialNum,
			&i.FullName,
			&i.DisplayName,
			&i.Address,
			&i.EmailAddress,
			&i.PhoneNumber,
			&i.BirthDate,
			&i.Gender,
			&i.MaritalStatus,
			&i.NumDependents,
			&i.NumChildren,
			&i.CinNum,
			&i.CnssNum,
			&i.HireDate,
			&i.Position,
			&i.CompensationPackageID,
			&i.BankRib,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesIncludingDeleted = `-- name: ListEmployeesIncludingDeleted :many
SELECT id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
FROM employee
ORDER BY org_id, serial_num
`

func (q *Queries) ListEmployeesIncludingDeleted(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeesIncludingDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SerialNum,
			&i.FullName,
			&i.DisplayName,
			&i.Address,
			&i.EmailAddress,
			&i.PhoneNumber,
			&i.BirthDate,
			&i.Gender,
			&i.MaritalStatus,
			&i.NumDependents,
			&i.NumChildren,
			&i.CinNum,
			&i.CnssNum,
			&i.HireDate,
			&i.Position,
			&i.CompensationPackageID,
			&i.BankRib,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreEmployee = `-- name: RestoreEmployee :one
UPDATE employee
SET
    updated_at = ?,
    deleted_at = NULL
WHERE
    id = ?
    AND deleted_at IS NOT NULL
RETURNING id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
`

type RestoreEmployeeParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RestoreEmployee(ctx context.Context, arg RestoreEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, restoreEmployee, arg.UpdatedAt, arg.ID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employee
SET
    full_name = ?,
    display_name = ?,
    address = ?,
    email_address = ?,
    phone_number = ?,
    birth_date = ?,
    gender = ?,
    marital_status = ?,
    num_dependents = ?,
    num_children = ?,
    cin_num = ?,
    cnss_num = ?,
    hire_date = ?,
    position = ?,
    compensation_package_id = ?,
    bank_rib = ?,
    updated_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
RETURNING id, org_id, serial_num, full_name, display_name, address, email_address, phone_number, birth_date, gender, marital_status, num_dependents, num_children, cin_num, cnss_num, hire_date, position, compensation_package_id, bank_rib, created_at, updated_at, deleted_at
`

type UpdateEmployeeParams struct {
	FullName              string         `json:"full_name"`
	DisplayName           sql.NullString `json:"display_name"`
	Address               sql.NullString `json:"address"`
	EmailAddress          sql.NullString `json:"email_address"`
	PhoneNumber           sql.NullString `json:"phone_number"`
	BirthDate             string         `json:"birth_date"`
	Gender                string         `json:"gender"`
	MaritalStatus         string         `json:"marital_status"`
	NumDependents         int64          `json:"num_dependents"`
	NumChildren           int64          `json:"num_children"`
	CinNum                string         `json:"cin_num"`
	CnssNum               sql.NullString `json:"cnss_num"`
	HireDate              string         `json:"hire_date"`
	Position              string         `json:"position"`
	CompensationPackageID string         `json:"compensation_package_id"`
	BankRib               sql.NullString `json:"bank_rib"`
	UpdatedAt             string         `json:"updated_at"`
	ID                    string         `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRowContext(ctx, updateEmployee,
		arg.FullName,
		arg.DisplayName,
		arg.Address,
		arg.EmailAddress,
		arg.PhoneNumber,
		arg.BirthDate,
		arg.Gender,
		arg.MaritalStatus,
		arg.NumDependents,
		arg.NumChildren,
		arg.CinNum,
		arg.CnssNum,
		arg.HireDate,
		arg.Position,
		arg.CompensationPackageID,
		arg.BankRib,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SerialNum,
		&i.FullName,
		&i.DisplayName,
		&i.Address,
		&i.EmailAddress,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Gender,
		&i.MaritalStatus,
		&i.NumDependents,
		&i.NumChildren,
		&i.CinNum,
		&i.CnssNum,
		&i.HireDate,
		&i.Position,
		&i.CompensationPackageID,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
