// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee_compensation_package.sql

package sqldb

import (
	"context"
	"database/sql"
)

const createEmployeeCompensationPackage = `-- name: CreateEmployeeCompensationPackage :one
INSERT INTO employee_compensation_package(
    id,
    currency,
    base_salary_cents,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, currency, base_salary_cents, created_at, updated_at, deleted_at
`

type CreateEmployeeCompensationPackageParams struct {
	ID              string `json:"id"`
	Currency        string `json:"currency"`
	BaseSalaryCents int64  `json:"base_salary_cents"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateEmployeeCompensationPackage(ctx context.Context, arg CreateEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error) {
	row := q.db.QueryRowContext(ctx, createEmployeeCompensationPackage,
		arg.ID,
		arg.Currency,
		arg.BaseSalaryCents,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmployeeCompensationPackage
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.BaseSalaryCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmployeeCompensationPackage = `-- name: DeleteEmployeeCompensationPackage :one
UPDATE employee_compensation_package
SET
    updated_at = ?,
    deleted_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
RETURNING id, currency, base_salary_cents, created_at, updated_at, deleted_at
`

type DeleteEmployeeCompensationPackageParams struct {
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteEmployeeCompensationPackage(ctx context.Context, arg DeleteEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error) {
	row := q.db.QueryRowContext(ctx, deleteEmployeeCompensationPackage, arg.UpdatedAt, arg.DeletedAt, arg.ID)
	var i EmployeeCompensationPackage
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.BaseSalaryCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeeCompensationPackage = `-- name: GetEmployeeCompensationPackage :one
SELECT id, currency, base_salary_cents, created_at, updated_at, deleted_at
FROM employee_compensation_package
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) GetEmployeeCompensationPackage(ctx context.Context, id string) (EmployeeCompensationPackage, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeCompensationPackage, id)
	var i EmployeeCompensationPackage
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.BaseSalaryCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmployeeCompensationPackageIncludingDeleted = `-- name: GetEmployeeCompensationPackageIncludingDeleted :one
SELECT id, currency, base_salary_cents, created_at, updated_at, deleted_at
FROM employee_compensation_package
WHERE id = ?
`

func (q *Queries) GetEmployeeCompensationPackageIncludingDeleted(ctx context.Context, id string) (EmployeeCompensationPackage, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeCompensationPackageIncludingDeleted, id)
	var i EmployeeCompensationPackage
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.BaseSalaryCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteEmployeeCompensationPackage = `-- name: HardDeleteEmployeeCompensationPackage :exec
DELETE FROM employee_compensation_package
WHERE id = ?
`

func (q *Queries) HardDeleteEmployeeCompensationPackage(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteEmployeeCompensationPackage, id)
	return err
}

const listEmployeeCompensationPackages = `-- name: ListEmployeeCompensationPackages :many
SELECT id, currency, base_salary_cents, created_at, updated_at, deleted_at
FROM employee_compensation_package
WHERE deleted_at IS NULL
`

func (q *Queries) ListEmployeeCompensationPackages(ctx context.Context) ([]EmployeeCompensationPackage, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeCompensationPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeCompensationPackage
	for rows.Next() {
		var i EmployeeCompensationPackage
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.BaseSalaryCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeCompensationPackagesIncludingDeleted = `-- name: ListEmployeeCompensationPackagesIncludingDeleted :many
SELECT id, currency, base_salary_cents, created_at, updated_at, deleted_at
FROM employee_compensation_package
`

func (q *Queries) ListEmployeeCompensationPackagesIncludingDeleted(ctx context.Context) ([]EmployeeCompensationPackage, error) {
	rows, err := q.db.QueryContext(ctx, listEmployeeCompensationPackagesIncludingDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmployeeCompensationPackage
	for rows.Next() {
		var i EmployeeCompensationPackage
		if err := rows.Scan(
			&i.ID,
			&i.Currency,
			&i.BaseSalaryCents,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreEmployeeCompensationPackage = `-- name: RestoreEmployeeCompensationPackage :one
UPDATE employee_compensation_package
SET
    updated_at = ?,
    deleted_at = NULL
WHERE
    id = ?
    AND deleted_at IS NOT NULL
RETURNING id, currency, base_salary_cents, created_at, updated_at, deleted_at
`

type RestoreEmployeeCompensationPackageParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RestoreEmployeeCompensationPackage(ctx context.Context, arg RestoreEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error) {
	row := q.db.QueryRowContext(ctx, restoreEmployeeCompensationPackage, arg.UpdatedAt, arg.ID)
	var i EmployeeCompensationPackage
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.BaseSalaryCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEmployeeCompensationPackage = `-- name: UpdateEmployeeCompensationPackage :one
UPDATE employee_compensation_package
SET
    currency = ?,
    base_salary_cents = ?,
    updated_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
RETURNING id, currency, base_salary_cents, created_at, updated_at, deleted_at
`

type UpdateEmployeeCompensationPackageParams struct {
	Currency        string `json:"currency"`
	BaseSalaryCents int64  `json:"base_salary_cents"`
	UpdatedAt       string `json:"updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateEmployeeCompensationPackage(ctx context.Context, arg UpdateEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error) {
	row := q.db.QueryRowContext(ctx, updateEmployeeCompensationPackage,
		arg.Currency,
		arg.BaseSalaryCents,
		arg.UpdatedAt,
		arg.ID,
	)
	var i EmployeeCompensationPackage
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.BaseSalaryCents,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
