// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"database/sql"
)

type AuditLog struct {
	ID        string         `json:"id"`
	TableName string         `json:"table_name"`
	RecordID  string         `json:"record_id"`
	Action    string         `json:"action"`
	Before    sql.NullString `json:"before"`
	After     string         `json:"after"`
	Timestamp string         `json:"timestamp"`
}

type Employee struct {
	ID                    string         `json:"id"`
	OrgID                 string         `json:"org_id"`
	SerialNum             int64          `json:"serial_num"`
	FullName              string         `json:"full_name"`
	DisplayName           sql.NullString `json:"display_name"`
	Address               sql.NullString `json:"address"`
	EmailAddress          sql.NullString `json:"email_address"`
	PhoneNumber           sql.NullString `json:"phone_number"`
	BirthDate             string         `json:"birth_date"`
	Gender                string         `json:"gender"`
	MaritalStatus         string         `json:"marital_status"`
	NumDependents         int64          `json:"num_dependents"`
	NumKids               int64          `json:"num_kids"`
	CinNum                string         `json:"cin_num"`
	CnssNum               sql.NullString `json:"cnss_num"`
	HireDate              string         `json:"hire_date"`
	Position              string         `json:"position"`
	CompensationPackageID string         `json:"compensation_package_id"`
	BankRib               sql.NullString `json:"bank_rib"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	DeletedAt             sql.NullString `json:"deleted_at"`
}

type EmployeeCompensationPackage struct {
	ID              string         `json:"id"`
	Currency        string         `json:"currency"`
	BaseSalaryCents int64          `json:"base_salary_cents"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	DeletedAt       sql.NullString `json:"deleted_at"`
}

type Organization struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Activity  sql.NullString `json:"activity"`
	LegalForm sql.NullString `json:"legal_form"`
	IceNum    sql.NullString `json:"ice_num"`
	IfNum     sql.NullString `json:"if_num"`
	RcNum     sql.NullString `json:"rc_num"`
	CnssNum   sql.NullString `json:"cnss_num"`
	BankRib   sql.NullString `json:"bank_rib"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
}

type PayrollPeriod struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Year        int64          `json:"year"`
	Month       int64          `json:"month"`
	Status      string         `json:"status"`
	FinalizedAt sql.NullString `json:"finalized_at"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
	DeletedAt   sql.NullString `json:"deleted_at"`
}

type PayrollResult struct {
	ID                                      string         `json:"id"`
	PayrollPeriodID                         string         `json:"payroll_period_id"`
	EmployeeID                              string         `json:"employee_id"`
	CompensationPackageID                   string         `json:"compensation_package_id"`
	Currency                                string         `json:"currency"`
	BaseSalaryCents                         int64          `json:"base_salary_cents"`
	SeniorityBonusCents                     int64          `json:"seniority_bonus_cents"`
	GrossSalaryCents                        int64          `json:"gross_salary_cents"`
	TotalOtherBonusCents                    int64          `json:"total_other_bonus_cents"`
	GrossSalaryGrandTotalCents              int64          `json:"gross_salary_grand_total_cents"`
	TotalExemptionsCents                    int64          `json:"total_exemptions_cents"`
	TaxableGrossSalaryCents                 int64          `json:"taxable_gross_salary_cents"`
	SocialAllowanceEmployeeContribCents     int64          `json:"social_allowance_employee_contrib_cents"`
	SocialAllowanceEmployerContribCents     int64          `json:"social_allowance_employer_contrib_cents"`
	JobLossCompensationEmployeeContribCents int64          `json:"job_loss_compensation_employee_contrib_cents"`
	JobLossCompensationEmployerContribCents int64          `json:"job_loss_compensation_employer_contrib_cents"`
	TrainingTaxEmployerContribCents         int64          `json:"training_tax_employer_contrib_cents"`
	FamilyBenefitsEmployerContribCents      int64          `json:"family_benefits_employer_contrib_cents"`
	TotalCnssEmployeeContribCents           int64          `json:"total_cnss_employee_contrib_cents"`
	TotalCnssEmployerContribCents           int64          `json:"total_cnss_employer_contrib_cents"`
	AmoEmployeeContribCents                 int64          `json:"amo_employee_contrib_cents"`
	AmoEmployerContribCents                 int64          `json:"amo_employer_contrib_cents"`
	TaxableNetSalaryCents                   int64          `json:"taxable_net_salary_cents"`
	IncomeTaxCents                          int64          `json:"income_tax_cents"`
	RoundingAmountCents                     int64          `json:"rounding_amount_cents"`
	NetToPayCents                           int64          `json:"net_to_pay_cents"`
	CreatedAt                               string         `json:"created_at"`
	UpdatedAt                               string         `json:"updated_at"`
	DeletedAt                               sql.NullString `json:"deleted_at"`
}
