// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization.sql

package sqldb

import (
	"context"
	"database/sql"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization(
    id,
    name,
    address,
    activity,
    legal_form,
    ice_num,
    if_num,
    rc_num,
    cnss_num,
    bank_rib,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Activity  sql.NullString `json:"activity"`
	LegalForm sql.NullString `json:"legal_form"`
	IceNum    sql.NullString `json:"ice_num"`
	IfNum     sql.NullString `json:"if_num"`
	RcNum     sql.NullString `json:"rc_num"`
	CnssNum   sql.NullString `json:"cnss_num"`
	BankRib   sql.NullString `json:"bank_rib"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Activity,
		arg.LegalForm,
		arg.IceNum,
		arg.IfNum,
		arg.RcNum,
		arg.CnssNum,
		arg.BankRib,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Activity,
		&i.LegalForm,
		&i.IceNum,
		&i.IfNum,
		&i.RcNum,
		&i.CnssNum,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :one
UPDATE organization
SET
    updated_at = ?,
    deleted_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
RETURNING id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
`

type DeleteOrganizationParams struct {
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeleteOrganization(ctx context.Context, arg DeleteOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, deleteOrganization, arg.UpdatedAt, arg.DeletedAt, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Activity,
		&i.LegalForm,
		&i.IceNum,
		&i.IfNum,
		&i.RcNum,
		&i.CnssNum,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
FROM organization
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) GetOrganization(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Activity,
		&i.LegalForm,
		&i.IceNum,
		&i.IfNum,
		&i.RcNum,
		&i.CnssNum,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationIncludingDeleted = `-- name: GetOrganizationIncludingDeleted :one
SELECT id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
FROM organization
WHERE id = ?
`

func (q *Queries) GetOrganizationIncludingDeleted(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationIncludingDeleted, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Activity,
		&i.LegalForm,
		&i.IceNum,
		&i.IfNum,
		&i.RcNum,
		&i.CnssNum,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeleteOrganization = `-- name: HardDeleteOrganization :exec
DELETE FROM organization
WHERE id = ?
`

func (q *Queries) HardDeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeleteOrganization, id)
	return err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
FROM organization
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Activity,
			&i.LegalForm,
			&i.IceNum,
			&i.IfNum,
			&i.RcNum,
			&i.CnssNum,
			&i.BankRib,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsIncludingDeleted = `-- name: ListOrganizationsIncludingDeleted :many
SELECT id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
FROM organization
ORDER BY name
`

func (q *Queries) ListOrganizationsIncludingDeleted(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsIncludingDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Activity,
			&i.LegalForm,
			&i.IceNum,
			&i.IfNum,
			&i.RcNum,
			&i.CnssNum,
			&i.BankRib,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreOrganization = `-- name: RestoreOrganization :one
UPDATE organization
SET
    updated_at = ?,
    deleted_at = NULL
WHERE
    id = ?
    AND deleted_at IS NOT NULL
RETURNING id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
`

type RestoreOrganizationParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RestoreOrganization(ctx context.Context, arg RestoreOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, restoreOrganization, arg.UpdatedAt, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Activity,
		&i.LegalForm,
		&i.IceNum,
		&i.IfNum,
		&i.RcNum,
		&i.CnssNum,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organization
SET
    name = ?,
    address = ?,
    activity = ?,
    legal_form = ?,
    ice_num = ?,
    if_num = ?,
    rc_num = ?,
    cnss_num = ?,
    bank_rib = ?,
    updated_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
RETURNING id, name, address, activity, legal_form, ice_num, if_num, rc_num, cnss_num, bank_rib, created_at, updated_at, deleted_at
`

type UpdateOrganizationParams struct {
	Name      string         `json:"name"`
	Address   sql.NullString `json:"address"`
	Activity  sql.NullString `json:"activity"`
	LegalForm sql.NullString `json:"legal_form"`
	IceNum    sql.NullString `json:"ice_num"`
	IfNum     sql.NullString `json:"if_num"`
	RcNum     sql.NullString `json:"rc_num"`
	CnssNum   sql.NullString `json:"cnss_num"`
	BankRib   sql.NullString `json:"bank_rib"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, updateOrganization,
		arg.Name,
		arg.Address,
		arg.Activity,
		arg.LegalForm,
		arg.IceNum,
		arg.IfNum,
		arg.RcNum,
		arg.CnssNum,
		arg.BankRib,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Activity,
		&i.LegalForm,
		&i.IceNum,
		&i.IfNum,
		&i.RcNum,
		&i.CnssNum,
		&i.BankRib,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
