// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payroll_period.sql

package sqldb

import (
	"context"
	"database/sql"
)

const createPayrollPeriod = `-- name: CreatePayrollPeriod :one
INSERT INTO payroll_period(
    id,
    org_id,
    year,
    month,
    status,
    finalized_at,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
`

type CreatePayrollPeriodParams struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	Year        int64          `json:"year"`
	Month       int64          `json:"month"`
	Status      string         `json:"status"`
	FinalizedAt sql.NullString `json:"finalized_at"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

func (q *Queries) CreatePayrollPeriod(ctx context.Context, arg CreatePayrollPeriodParams) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, createPayrollPeriod,
		arg.ID,
		arg.OrgID,
		arg.Year,
		arg.Month,
		arg.Status,
		arg.FinalizedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePayrollPeriod = `-- name: DeletePayrollPeriod :exec
UPDATE payroll_period
SET
    updated_at = ?,
    deleted_at = ?
WHERE
    id = ?
    AND deleted_at IS NULL
`

type DeletePayrollPeriodParams struct {
	UpdatedAt string         `json:"updated_at"`
	DeletedAt sql.NullString `json:"deleted_at"`
	ID        string         `json:"id"`
}

func (q *Queries) DeletePayrollPeriod(ctx context.Context, arg DeletePayrollPeriodParams) error {
	_, err := q.db.ExecContext(ctx, deletePayrollPeriod, arg.UpdatedAt, arg.DeletedAt, arg.ID)
	return err
}

const finalizePayrollPeriod = `-- name: FinalizePayrollPeriod :one
UPDATE payroll_period
SET
    status = 'FINALIZED',
    finalized_at = ?,
    updated_at = ?
WHERE
    id = ?
    AND status = 'DRAFT'
    AND deleted_at IS NULL
RETURNING id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
`

type FinalizePayrollPeriodParams struct {
	FinalizedAt sql.NullString `json:"finalized_at"`
	UpdatedAt   string         `json:"updated_at"`
	ID          string         `json:"id"`
}

func (q *Queries) FinalizePayrollPeriod(ctx context.Context, arg FinalizePayrollPeriodParams) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, finalizePayrollPeriod, arg.FinalizedAt, arg.UpdatedAt, arg.ID)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPayrollPeriod = `-- name: GetPayrollPeriod :one
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) GetPayrollPeriod(ctx context.Context, id string) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, getPayrollPeriod, id)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPayrollPeriodByOrgYearMonth = `-- name: GetPayrollPeriodByOrgYearMonth :one
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE
    org_id = ?
    AND year = ?
    AND month = ?
    AND deleted_at IS NULL
`

type GetPayrollPeriodByOrgYearMonthParams struct {
	OrgID string `json:"org_id"`
	Year  int64  `json:"year"`
	Month int64  `json:"month"`
}

func (q *Queries) GetPayrollPeriodByOrgYearMonth(ctx context.Context, arg GetPayrollPeriodByOrgYearMonthParams) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, getPayrollPeriodByOrgYearMonth, arg.OrgID, arg.Year, arg.Month)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPayrollPeriodByOrgYearMonthIncludingDeleted = `-- name: GetPayrollPeriodByOrgYearMonthIncludingDeleted :one
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE
    org_id = ?
    AND year = ?
    AND month = ?
`

type GetPayrollPeriodByOrgYearMonthIncludingDeletedParams struct {
	OrgID string `json:"org_id"`
	Year  int64  `json:"year"`
	Month int64  `json:"month"`
}

func (q *Queries) GetPayrollPeriodByOrgYearMonthIncludingDeleted(ctx context.Context, arg GetPayrollPeriodByOrgYearMonthIncludingDeletedParams) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, getPayrollPeriodByOrgYearMonthIncludingDeleted, arg.OrgID, arg.Year, arg.Month)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPayrollPeriodIncludingDeleted = `-- name: GetPayrollPeriodIncludingDeleted :one
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE id = ?
`

func (q *Queries) GetPayrollPeriodIncludingDeleted(ctx context.Context, id string) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, getPayrollPeriodIncludingDeleted, id)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const hardDeletePayrollPeriod = `-- name: HardDeletePayrollPeriod :exec
DELETE FROM payroll_period
WHERE id = ?
`

func (q *Queries) HardDeletePayrollPeriod(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, hardDeletePayrollPeriod, id)
	return err
}

const listDraftPayrollPeriods = `-- name: ListDraftPayrollPeriods :many
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE
    status = 'DRAFT'
    AND deleted_at IS NULL
ORDER BY
    year DESC,
    month DESC
`

func (q *Queries) ListDraftPayrollPeriods(ctx context.Context) ([]PayrollPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listDraftPayrollPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPeriod
	for rows.Next() {
		var i PayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftPayrollPeriodsIncludingDeleted = `-- name: ListDraftPayrollPeriodsIncludingDeleted :many
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE status = 'DRAFT'
ORDER BY
    year DESC,
    month DESC
`

func (q *Queries) ListDraftPayrollPeriodsIncludingDeleted(ctx context.Context) ([]PayrollPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listDraftPayrollPeriodsIncludingDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPeriod
	for rows.Next() {
		var i PayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPeriods = `-- name: ListPayrollPeriods :many
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE deleted_at IS NULL
ORDER BY
    year DESC,
    month DESC
`

func (q *Queries) ListPayrollPeriods(ctx context.Context) ([]PayrollPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listPayrollPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPeriod
	for rows.Next() {
		var i PayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPeriodsByOrganization = `-- name: ListPayrollPeriodsByOrganization :many
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE
    org_id = ?
    AND deleted_at IS NULL
ORDER BY
    year DESC,
    month DESC
`

func (q *Queries) ListPayrollPeriodsByOrganization(ctx context.Context, orgID string) ([]PayrollPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listPayrollPeriodsByOrganization, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPeriod
	for rows.Next() {
		var i PayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPeriodsByOrganizationIncludingDeleted = `-- name: ListPayrollPeriodsByOrganizationIncludingDeleted :many
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
WHERE
    org_id = ?
ORDER BY
    year DESC,
    month DESC
`

func (q *Queries) ListPayrollPeriodsByOrganizationIncludingDeleted(ctx context.Context, orgID string) ([]PayrollPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listPayrollPeriodsByOrganizationIncludingDeleted, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPeriod
	for rows.Next() {
		var i PayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollPeriodsIncludingDeleted = `-- name: ListPayrollPeriodsIncludingDeleted :many
SELECT id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
FROM payroll_period
ORDER BY
    year DESC,
    month DESC
`

func (q *Queries) ListPayrollPeriodsIncludingDeleted(ctx context.Context) ([]PayrollPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listPayrollPeriodsIncludingDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PayrollPeriod
	for rows.Next() {
		var i PayrollPeriod
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Year,
			&i.Month,
			&i.Status,
			&i.FinalizedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePayrollPeriod = `-- name: RestorePayrollPeriod :one
UPDATE payroll_period
SET
    updated_at = ?,
    deleted_at = NULL
WHERE
    id = ?
    AND deleted_at IS NOT NULL
RETURNING id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
`

type RestorePayrollPeriodParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) RestorePayrollPeriod(ctx context.Context, arg RestorePayrollPeriodParams) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, restorePayrollPeriod, arg.UpdatedAt, arg.ID)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const unfinalizePayrollPeriod = `-- name: UnfinalizePayrollPeriod :one
UPDATE payroll_period
SET
    status = 'DRAFT',
    finalized_at = NULL,
    updated_at = ?
WHERE
    id = ?
    AND status = 'FINALIZED'
    AND deleted_at IS NULL
RETURNING id, org_id, year, month, status, finalized_at, created_at, updated_at, deleted_at
`

type UnfinalizePayrollPeriodParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) UnfinalizePayrollPeriod(ctx context.Context, arg UnfinalizePayrollPeriodParams) (PayrollPeriod, error) {
	row := q.db.QueryRowContext(ctx, unfinalizePayrollPeriod, arg.UpdatedAt, arg.ID)
	var i PayrollPeriod
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.FinalizedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
