// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"context"
)

type Querier interface {
	CountEmployeesUsingCompensationPackage(ctx context.Context, compensationPackageID string) (int64, error)
	CountPayrollResultsUsingCompensationPackage(ctx context.Context, compensationPackageID string) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	CreateEmployeeCompensationPackage(ctx context.Context, arg CreateEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePayrollPeriod(ctx context.Context, arg CreatePayrollPeriodParams) (PayrollPeriod, error)
	CreatePayrollResult(ctx context.Context, arg CreatePayrollResultParams) (PayrollResult, error)
	DeleteEmployee(ctx context.Context, arg DeleteEmployeeParams) (Employee, error)
	DeleteEmployeeCompensationPackage(ctx context.Context, arg DeleteEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error)
	DeleteOrganization(ctx context.Context, arg DeleteOrganizationParams) (Organization, error)
	DeletePayrollPeriod(ctx context.Context, arg DeletePayrollPeriodParams) (PayrollPeriod, error)
	DeletePayrollResult(ctx context.Context, arg DeletePayrollResultParams) (PayrollResult, error)
	FinalizePayrollPeriod(ctx context.Context, arg FinalizePayrollPeriodParams) (PayrollPeriod, error)
	GetEmployee(ctx context.Context, id string) (Employee, error)
	GetEmployeeByOrgAndSerialNum(ctx context.Context, arg GetEmployeeByOrgAndSerialNumParams) (Employee, error)
	GetEmployeeCompensationPackage(ctx context.Context, id string) (EmployeeCompensationPackage, error)
	GetEmployeeCompensationPackageIncludingDeleted(ctx context.Context, id string) (EmployeeCompensationPackage, error)
	GetEmployeeIncludingDeleted(ctx context.Context, id string) (Employee, error)
	GetNextSerialNumber(ctx context.Context, orgID string) (int64, error)
	GetOrganization(ctx context.Context, id string) (Organization, error)
	GetOrganizationIncludingDeleted(ctx context.Context, id string) (Organization, error)
	GetPayrollPeriod(ctx context.Context, id string) (PayrollPeriod, error)
	GetPayrollPeriodByOrgYearMonth(ctx context.Context, arg GetPayrollPeriodByOrgYearMonthParams) (PayrollPeriod, error)
	GetPayrollPeriodByOrgYearMonthIncludingDeleted(ctx context.Context, arg GetPayrollPeriodByOrgYearMonthIncludingDeletedParams) (PayrollPeriod, error)
	GetPayrollPeriodIncludingDeleted(ctx context.Context, id string) (PayrollPeriod, error)
	GetPayrollResult(ctx context.Context, id string) (PayrollResult, error)
	GetPayrollResultIncludingDeleted(ctx context.Context, id string) (PayrollResult, error)
	HardDeleteEmployee(ctx context.Context, id string) error
	HardDeleteEmployeeCompensationPackage(ctx context.Context, id string) error
	HardDeleteOrganization(ctx context.Context, id string) error
	HardDeletePayrollPeriod(ctx context.Context, id string) error
	HardDeletePayrollResult(ctx context.Context, id string) error
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error)
	ListAuditLogsForRecord(ctx context.Context, arg ListAuditLogsForRecordParams) ([]AuditLog, error)
	ListAuditLogsRecent(ctx context.Context, limit int64) ([]AuditLog, error)
	ListDraftPayrollPeriods(ctx context.Context) ([]PayrollPeriod, error)
	ListDraftPayrollPeriodsIncludingDeleted(ctx context.Context) ([]PayrollPeriod, error)
	ListEmployeeCompensationPackages(ctx context.Context) ([]EmployeeCompensationPackage, error)
	ListEmployeeCompensationPackagesIncludingDeleted(ctx context.Context) ([]EmployeeCompensationPackage, error)
	ListEmployees(ctx context.Context) ([]Employee, error)
	ListEmployeesByOrganization(ctx context.Context, orgID string) ([]Employee, error)
	ListEmployeesByOrganizationIncludingDeleted(ctx context.Context, orgID string) ([]Employee, error)
	ListEmployeesIncludingDeleted(ctx context.Context) ([]Employee, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListOrganizationsIncludingDeleted(ctx context.Context) ([]Organization, error)
	ListPayrollPeriods(ctx context.Context) ([]PayrollPeriod, error)
	ListPayrollPeriodsByOrganization(ctx context.Context, orgID string) ([]PayrollPeriod, error)
	ListPayrollPeriodsByOrganizationIncludingDeleted(ctx context.Context, orgID string) ([]PayrollPeriod, error)
	ListPayrollPeriodsIncludingDeleted(ctx context.Context) ([]PayrollPeriod, error)
	ListPayrollResults(ctx context.Context) ([]PayrollResult, error)
	ListPayrollResultsByEmployee(ctx context.Context, employeeID string) ([]PayrollResult, error)
	ListPayrollResultsByEmployeeIncludingDeleted(ctx context.Context, employeeID string) ([]PayrollResult, error)
	ListPayrollResultsByPayrollPeriod(ctx context.Context, payrollPeriodID string) ([]PayrollResult, error)
	ListPayrollResultsByPayrollPeriodIncludingDeleted(ctx context.Context, payrollPeriodID string) ([]PayrollResult, error)
	ListPayrollResultsIncludingDeleted(ctx context.Context) ([]PayrollResult, error)
	RestoreEmployee(ctx context.Context, arg RestoreEmployeeParams) (Employee, error)
	RestoreEmployeeCompensationPackage(ctx context.Context, arg RestoreEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error)
	RestoreOrganization(ctx context.Context, arg RestoreOrganizationParams) (Organization, error)
	RestorePayrollPeriod(ctx context.Context, arg RestorePayrollPeriodParams) (PayrollPeriod, error)
	RestorePayrollResult(ctx context.Context, arg RestorePayrollResultParams) (PayrollResult, error)
	UnfinalizePayrollPeriod(ctx context.Context, arg UnfinalizePayrollPeriodParams) (PayrollPeriod, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
	UpdateEmployeeCompensationPackage(ctx context.Context, arg UpdateEmployeeCompensationPackageParams) (EmployeeCompensationPackage, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
}

var _ Querier = (*Queries)(nil)
